import AboutContainer from '../../feature/ClientShared/components/aboutContainer/AboutContainer'
import React from 'react'
import LayoutClient from '../../layoutClient/LayoutClient'
import {serverSideTranslations} from "next-i18next/serverSideTranslations"
import Head from 'next/head'


export const getStaticProps = async ({locale})=>({
  props:{
      ...(await serverSideTranslations(locale, ["common"]))
  }
})

const AboutUs = () => {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutClient>
        <AboutContainer/>
      </LayoutClient>
      
    </div>
  )
}

export default AboutUs