// import type { NextPage } from "next";
import Head from "next/head";
import LayoutClient from "../layoutClient/LayoutClient";
import HomePage from "../pages/home/index";

// import {serverSideTranslations} from "next-i18next/serverSideTranslations"
// import { useTranslation } from "next-i18next";

// export const getStaticProps = async ({locale})=>({
//   props:{
//       ...(await serverSideTranslations(locale, ["common"]))
//   }
// })

const Home = () => {
  // const {t, i18n} = useTranslation()

  // const handleUpload = (e: any) => {
  //   const file = e.target.files[0];
  //   const formData = new FormData();
  //   formData.append("file", file);

  //   axios({
  //     method: "POST",
  //     url: "/api/uploads",
  //     headers: {
  //       "Content-Type": "multi-part",
  //     },
  //     data: formData,
  //   });
  // };



  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutClient>
        <HomePage />
      </LayoutClient>
    </div>
  );
};

export default Home;
